// Code generated by internal/tools/pbgen from internal/migrations. DO NOT EDIT.
// Regenerate with `go generate ./...` after changing a migration.

package schema

import (
	"time"

	"github.com/pocketbase/pocketbase/core"
)

// Collections lists every collection the typed layer depends on; see Verify.
var Collections = []CollectionSpec{
	ProductsSpec,
	ProductVariationsSpec,
	ModifierListsSpec,
	CartsSpec,
	OrdersSpec,
	WebhookEventsSpec,
	UsersSpec,
}

// ---------------------------------------------------------------------------
// products
// ---------------------------------------------------------------------------

const ProductsCollection = "products"

// ProductsID is the ID of a "products" record.
type ProductsID string

// ProductsRecord is a typed proxy for a "products" record.
type ProductsRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*ProductsRecord)(nil)

func (*ProductsRecord) CollectionName() string { return ProductsCollection }

func (r *ProductsRecord) ID() ProductsID { return ProductsID(r.Id) }

func (r *ProductsRecord) Slug() string { return r.GetString("slug") }

func (r *ProductsRecord) SetSlug(v string) { r.Set("slug", v) }

func (r *ProductsRecord) Name() string { return r.GetString("name") }

func (r *ProductsRecord) SetName(v string) { r.Set("name", v) }

func (r *ProductsRecord) Category() ProductsCategory {
	return ProductsCategory(r.GetString("category"))
}

func (r *ProductsRecord) SetCategory(v ProductsCategory) { r.Set("category", string(v)) }

func (r *ProductsRecord) Tagline() string { return r.GetString("tagline") }

func (r *ProductsRecord) SetTagline(v string) { r.Set("tagline", v) }

func (r *ProductsRecord) Description() string { return r.GetString("description") }

func (r *ProductsRecord) SetDescription(v string) { r.Set("description", v) }

func (r *ProductsRecord) Ingredients() ([]string, error) {
	return getJSON[[]string](r.Record, "ingredients")
}

func (r *ProductsRecord) SetIngredients(v []string) { r.Set("ingredients", v) }

func (r *ProductsRecord) Size() string { return r.GetString("size") }

func (r *ProductsRecord) SetSize(v string) { r.Set("size", v) }

func (r *ProductsRecord) PourTop() string { return r.GetString("pour_top") }

func (r *ProductsRecord) SetPourTop(v string) { r.Set("pour_top", v) }

func (r *ProductsRecord) PourBottom() string { return r.GetString("pour_bottom") }

func (r *ProductsRecord) SetPourBottom(v string) { r.Set("pour_bottom", v) }

func (r *ProductsRecord) Badge() string { return r.GetString("badge") }

func (r *ProductsRecord) SetBadge(v string) { r.Set("badge", v) }

func (r *ProductsRecord) Created() time.Time { return getTime(r.Record, "created") }

func (r *ProductsRecord) Updated() time.Time { return getTime(r.Record, "updated") }

func (r *ProductsRecord) SquareItemID() string { return r.GetString("square_item_id") }

func (r *ProductsRecord) SetSquareItemID(v string) { r.Set("square_item_id", v) }

func (r *ProductsRecord) CatalogStatus() ProductsCatalogStatus {
	return ProductsCatalogStatus(r.GetString("catalog_status"))
}

func (r *ProductsRecord) SetCatalogStatus(v ProductsCatalogStatus) {
	r.Set("catalog_status", string(v))
}

func (r *ProductsRecord) SquareVersion() int64 { return getInt64(r.Record, "square_version") }

func (r *ProductsRecord) SetSquareVersion(v int64) { r.Set("square_version", v) }

func (r *ProductsRecord) ModifierLists() ([]ProductModifierListRef, error) {
	return getJSON[[]ProductModifierListRef](r.Record, "modifier_lists")
}

func (r *ProductsRecord) SetModifierLists(v []ProductModifierListRef) { r.Set("modifier_lists", v) }

func (r *ProductsRecord) SortOrder() int64 { return getInt64(r.Record, "sort_order") }

func (r *ProductsRecord) SetSortOrder(v int64) { r.Set("sort_order", v) }

func (r *ProductsRecord) SyncedAt() time.Time { return getTime(r.Record, "synced_at") }

func (r *ProductsRecord) SetSyncedAt(v time.Time) { setTime(r.Record, "synced_at", v) }

// ProductsCategory mirrors the options of products.category.
type ProductsCategory string

const (
	ProductsCategorySignature ProductsCategory = "signature"
	ProductsCategoryPantry    ProductsCategory = "pantry"
	ProductsCategoryMerch     ProductsCategory = "merch"
	ProductsCategoryMatcha    ProductsCategory = "matcha"
)

// ProductsCategoryValues lists every option of products.category.
var ProductsCategoryValues = []ProductsCategory{ProductsCategorySignature, ProductsCategoryPantry, ProductsCategoryMerch, ProductsCategoryMatcha}

// ProductsCatalogStatus mirrors the options of products.catalog_status.
type ProductsCatalogStatus string

const (
	ProductsCatalogStatusUnlinked ProductsCatalogStatus = "unlinked"
	ProductsCatalogStatusActive   ProductsCatalogStatus = "active"
	ProductsCatalogStatusArchived ProductsCatalogStatus = "archived"
	ProductsCatalogStatusDeleted  ProductsCatalogStatus = "deleted"
)

// ProductsCatalogStatusValues lists every option of products.catalog_status.
var ProductsCatalogStatusValues = []ProductsCatalogStatus{ProductsCatalogStatusUnlinked, ProductsCatalogStatusActive, ProductsCatalogStatusArchived, ProductsCatalogStatusDeleted}

// Products holds typed column references for building "products" queries.
var Products = struct {
	ID            Column[ProductsID]
	Slug          Column[string]
	Name          Column[string]
	Category      Column[ProductsCategory]
	Tagline       Column[string]
	Description   Column[string]
	Size          Column[string]
	PourTop       Column[string]
	PourBottom    Column[string]
	Badge         Column[string]
	Created       Column[time.Time]
	Updated       Column[time.Time]
	SquareItemID  Column[string]
	CatalogStatus Column[ProductsCatalogStatus]
	SquareVersion Column[int64]
	SortOrder     Column[int64]
	SyncedAt      Column[time.Time]
}{
	ID:            Column[ProductsID]{name: "id"},
	Slug:          Column[string]{name: "slug"},
	Name:          Column[string]{name: "name"},
	Category:      Column[ProductsCategory]{name: "category"},
	Tagline:       Column[string]{name: "tagline"},
	Description:   Column[string]{name: "description"},
	Size:          Column[string]{name: "size"},
	PourTop:       Column[string]{name: "pour_top"},
	PourBottom:    Column[string]{name: "pour_bottom"},
	Badge:         Column[string]{name: "badge"},
	Created:       Column[time.Time]{name: "created"},
	Updated:       Column[time.Time]{name: "updated"},
	SquareItemID:  Column[string]{name: "square_item_id"},
	CatalogStatus: Column[ProductsCatalogStatus]{name: "catalog_status"},
	SquareVersion: Column[int64]{name: "square_version"},
	SortOrder:     Column[int64]{name: "sort_order"},
	SyncedAt:      Column[time.Time]{name: "synced_at"},
}

var ProductsSpec = CollectionSpec{
	Name: "products",
	Type: "base",
	Fields: []FieldSpec{
		{Name: "slug", Type: "text"},
		{Name: "name", Type: "text"},
		{Name: "category", Type: "select", Values: []string{"signature", "pantry", "merch", "matcha"}},
		{Name: "tagline", Type: "text"},
		{Name: "description", Type: "text"},
		{Name: "ingredients", Type: "json"},
		{Name: "size", Type: "text"},
		{Name: "pour_top", Type: "text"},
		{Name: "pour_bottom", Type: "text"},
		{Name: "badge", Type: "text"},
		{Name: "created", Type: "autodate"},
		{Name: "updated", Type: "autodate"},
		{Name: "square_item_id", Type: "text"},
		{Name: "catalog_status", Type: "select", Values: []string{"unlinked", "active", "archived", "deleted"}},
		{Name: "square_version", Type: "number", OnlyInt: true},
		{Name: "modifier_lists", Type: "json"},
		{Name: "sort_order", Type: "number", OnlyInt: true},
		{Name: "synced_at", Type: "date"},
	},
}

// ---------------------------------------------------------------------------
// product_variations
// ---------------------------------------------------------------------------

const ProductVariationsCollection = "product_variations"

// ProductVariationsID is the ID of a "product_variations" record.
type ProductVariationsID string

// ProductVariationsRecord is a typed proxy for a "product_variations" record.
type ProductVariationsRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*ProductVariationsRecord)(nil)

func (*ProductVariationsRecord) CollectionName() string { return ProductVariationsCollection }

func (r *ProductVariationsRecord) ID() ProductVariationsID { return ProductVariationsID(r.Id) }

func (r *ProductVariationsRecord) Product() ProductsID { return ProductsID(r.GetString("product")) }

func (r *ProductVariationsRecord) SetProduct(v ProductsID) { r.Set("product", string(v)) }

func (r *ProductVariationsRecord) SquareVariationID() string {
	return r.GetString("square_variation_id")
}

func (r *ProductVariationsRecord) SetSquareVariationID(v string) { r.Set("square_variation_id", v) }

func (r *ProductVariationsRecord) Name() string { return r.GetString("name") }

func (r *ProductVariationsRecord) SetName(v string) { r.Set("name", v) }

func (r *ProductVariationsRecord) PriceAmount() int64 { return getInt64(r.Record, "price_amount") }

func (r *ProductVariationsRecord) SetPriceAmount(v int64) { r.Set("price_amount", v) }

func (r *ProductVariationsRecord) Currency() string { return r.GetString("currency") }

func (r *ProductVariationsRecord) SetCurrency(v string) { r.Set("currency", v) }

func (r *ProductVariationsRecord) Sellable() bool { return r.GetBool("sellable") }

func (r *ProductVariationsRecord) SetSellable(v bool) { r.Set("sellable", v) }

func (r *ProductVariationsRecord) Ordinal() int64 { return getInt64(r.Record, "ordinal") }

func (r *ProductVariationsRecord) SetOrdinal(v int64) { r.Set("ordinal", v) }

func (r *ProductVariationsRecord) SquareVersion() int64 { return getInt64(r.Record, "square_version") }

func (r *ProductVariationsRecord) SetSquareVersion(v int64) { r.Set("square_version", v) }

func (r *ProductVariationsRecord) Created() time.Time { return getTime(r.Record, "created") }

func (r *ProductVariationsRecord) Updated() time.Time { return getTime(r.Record, "updated") }

// ProductVariations holds typed column references for building "product_variations" queries.
var ProductVariations = struct {
	ID                Column[ProductVariationsID]
	Product           Column[ProductsID]
	SquareVariationID Column[string]
	Name              Column[string]
	PriceAmount       Column[int64]
	Currency          Column[string]
	Sellable          Column[bool]
	Ordinal           Column[int64]
	SquareVersion     Column[int64]
	Created           Column[time.Time]
	Updated           Column[time.Time]
}{
	ID:                Column[ProductVariationsID]{name: "id"},
	Product:           Column[ProductsID]{name: "product"},
	SquareVariationID: Column[string]{name: "square_variation_id"},
	Name:              Column[string]{name: "name"},
	PriceAmount:       Column[int64]{name: "price_amount"},
	Currency:          Column[string]{name: "currency"},
	Sellable:          Column[bool]{name: "sellable"},
	Ordinal:           Column[int64]{name: "ordinal"},
	SquareVersion:     Column[int64]{name: "square_version"},
	Created:           Column[time.Time]{name: "created"},
	Updated:           Column[time.Time]{name: "updated"},
}

var ProductVariationsSpec = CollectionSpec{
	Name: "product_variations",
	Type: "base",
	Fields: []FieldSpec{
		{Name: "product", Type: "relation", Relation: "products"},
		{Name: "square_variation_id", Type: "text"},
		{Name: "name", Type: "text"},
		{Name: "price_amount", Type: "number", OnlyInt: true},
		{Name: "currency", Type: "text"},
		{Name: "sellable", Type: "bool"},
		{Name: "ordinal", Type: "number", OnlyInt: true},
		{Name: "square_version", Type: "number", OnlyInt: true},
		{Name: "created", Type: "autodate"},
		{Name: "updated", Type: "autodate"},
	},
}

// ---------------------------------------------------------------------------
// modifier_lists
// ---------------------------------------------------------------------------

const ModifierListsCollection = "modifier_lists"

// ModifierListsID is the ID of a "modifier_lists" record.
type ModifierListsID string

// ModifierListsRecord is a typed proxy for a "modifier_lists" record.
type ModifierListsRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*ModifierListsRecord)(nil)

func (*ModifierListsRecord) CollectionName() string { return ModifierListsCollection }

func (r *ModifierListsRecord) ID() ModifierListsID { return ModifierListsID(r.Id) }

func (r *ModifierListsRecord) SquareModifierListID() string {
	return r.GetString("square_modifier_list_id")
}

func (r *ModifierListsRecord) SetSquareModifierListID(v string) { r.Set("square_modifier_list_id", v) }

func (r *ModifierListsRecord) Name() string { return r.GetString("name") }

func (r *ModifierListsRecord) SetName(v string) { r.Set("name", v) }

func (r *ModifierListsRecord) MinSelected() int64 { return getInt64(r.Record, "min_selected") }

func (r *ModifierListsRecord) SetMinSelected(v int64) { r.Set("min_selected", v) }

func (r *ModifierListsRecord) MaxSelected() int64 { return getInt64(r.Record, "max_selected") }

func (r *ModifierListsRecord) SetMaxSelected(v int64) { r.Set("max_selected", v) }

func (r *ModifierListsRecord) Modifiers() ([]ModifierJSON, error) {
	return getJSON[[]ModifierJSON](r.Record, "modifiers")
}

func (r *ModifierListsRecord) SetModifiers(v []ModifierJSON) { r.Set("modifiers", v) }

func (r *ModifierListsRecord) SquareVersion() int64 { return getInt64(r.Record, "square_version") }

func (r *ModifierListsRecord) SetSquareVersion(v int64) { r.Set("square_version", v) }

func (r *ModifierListsRecord) Created() time.Time { return getTime(r.Record, "created") }

func (r *ModifierListsRecord) Updated() time.Time { return getTime(r.Record, "updated") }

// ModifierLists holds typed column references for building "modifier_lists" queries.
var ModifierLists = struct {
	ID                   Column[ModifierListsID]
	SquareModifierListID Column[string]
	Name                 Column[string]
	MinSelected          Column[int64]
	MaxSelected          Column[int64]
	SquareVersion        Column[int64]
	Created              Column[time.Time]
	Updated              Column[time.Time]
}{
	ID:                   Column[ModifierListsID]{name: "id"},
	SquareModifierListID: Column[string]{name: "square_modifier_list_id"},
	Name:                 Column[string]{name: "name"},
	MinSelected:          Column[int64]{name: "min_selected"},
	MaxSelected:          Column[int64]{name: "max_selected"},
	SquareVersion:        Column[int64]{name: "square_version"},
	Created:              Column[time.Time]{name: "created"},
	Updated:              Column[time.Time]{name: "updated"},
}

var ModifierListsSpec = CollectionSpec{
	Name: "modifier_lists",
	Type: "base",
	Fields: []FieldSpec{
		{Name: "square_modifier_list_id", Type: "text"},
		{Name: "name", Type: "text"},
		{Name: "min_selected", Type: "number", OnlyInt: true},
		{Name: "max_selected", Type: "number", OnlyInt: true},
		{Name: "modifiers", Type: "json"},
		{Name: "square_version", Type: "number", OnlyInt: true},
		{Name: "created", Type: "autodate"},
		{Name: "updated", Type: "autodate"},
	},
}

// ---------------------------------------------------------------------------
// carts
// ---------------------------------------------------------------------------

const CartsCollection = "carts"

// CartsID is the ID of a "carts" record.
type CartsID string

// CartsRecord is a typed proxy for a "carts" record.
type CartsRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*CartsRecord)(nil)

func (*CartsRecord) CollectionName() string { return CartsCollection }

func (r *CartsRecord) ID() CartsID { return CartsID(r.Id) }

func (r *CartsRecord) User() UsersID { return UsersID(r.GetString("user")) }

func (r *CartsRecord) SetUser(v UsersID) { r.Set("user", string(v)) }

func (r *CartsRecord) TokenHash() string { return r.GetString("token_hash") }

func (r *CartsRecord) SetTokenHash(v string) { r.Set("token_hash", v) }

func (r *CartsRecord) Items() ([]CartItemJSON, error) {
	return getJSON[[]CartItemJSON](r.Record, "items")
}

func (r *CartsRecord) SetItems(v []CartItemJSON) { r.Set("items", v) }

func (r *CartsRecord) Created() time.Time { return getTime(r.Record, "created") }

func (r *CartsRecord) Updated() time.Time { return getTime(r.Record, "updated") }

// Carts holds typed column references for building "carts" queries.
var Carts = struct {
	ID        Column[CartsID]
	User      Column[UsersID]
	TokenHash Column[string]
	Created   Column[time.Time]
	Updated   Column[time.Time]
}{
	ID:        Column[CartsID]{name: "id"},
	User:      Column[UsersID]{name: "user"},
	TokenHash: Column[string]{name: "token_hash"},
	Created:   Column[time.Time]{name: "created"},
	Updated:   Column[time.Time]{name: "updated"},
}

var CartsSpec = CollectionSpec{
	Name: "carts",
	Type: "base",
	Fields: []FieldSpec{
		{Name: "user", Type: "relation", Relation: "users"},
		{Name: "token_hash", Type: "text"},
		{Name: "items", Type: "json"},
		{Name: "created", Type: "autodate"},
		{Name: "updated", Type: "autodate"},
	},
}

// ---------------------------------------------------------------------------
// orders
// ---------------------------------------------------------------------------

const OrdersCollection = "orders"

// OrdersID is the ID of a "orders" record.
type OrdersID string

// OrdersRecord is a typed proxy for a "orders" record.
type OrdersRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*OrdersRecord)(nil)

func (*OrdersRecord) CollectionName() string { return OrdersCollection }

func (r *OrdersRecord) ID() OrdersID { return OrdersID(r.Id) }

func (r *OrdersRecord) Status() OrdersStatus { return OrdersStatus(r.GetString("status")) }

func (r *OrdersRecord) SetStatus(v OrdersStatus) { r.Set("status", string(v)) }

func (r *OrdersRecord) CustomerName() string { return r.GetString("customer_name") }

func (r *OrdersRecord) SetCustomerName(v string) { r.Set("customer_name", v) }

func (r *OrdersRecord) CustomerEmail() string { return r.GetString("customer_email") }

func (r *OrdersRecord) SetCustomerEmail(v string) { r.Set("customer_email", v) }

func (r *OrdersRecord) CustomerPhone() string { return r.GetString("customer_phone") }

func (r *OrdersRecord) SetCustomerPhone(v string) { r.Set("customer_phone", v) }

func (r *OrdersRecord) Notes() string { return r.GetString("notes") }

func (r *OrdersRecord) SetNotes(v string) { r.Set("notes", v) }

func (r *OrdersRecord) Created() time.Time { return getTime(r.Record, "created") }

func (r *OrdersRecord) Updated() time.Time { return getTime(r.Record, "updated") }

func (r *OrdersRecord) User() UsersID { return UsersID(r.GetString("user")) }

func (r *OrdersRecord) SetUser(v UsersID) { r.Set("user", string(v)) }

func (r *OrdersRecord) LineItems() ([]OrderLineItemJSON, error) {
	return getJSON[[]OrderLineItemJSON](r.Record, "line_items")
}

func (r *OrdersRecord) SetLineItems(v []OrderLineItemJSON) { r.Set("line_items", v) }

func (r *OrdersRecord) Currency() string { return r.GetString("currency") }

func (r *OrdersRecord) SetCurrency(v string) { r.Set("currency", v) }

func (r *OrdersRecord) SubtotalAmount() int64 { return getInt64(r.Record, "subtotal_amount") }

func (r *OrdersRecord) SetSubtotalAmount(v int64) { r.Set("subtotal_amount", v) }

func (r *OrdersRecord) TaxAmount() int64 { return getInt64(r.Record, "tax_amount") }

func (r *OrdersRecord) SetTaxAmount(v int64) { r.Set("tax_amount", v) }

func (r *OrdersRecord) TotalAmount() int64 { return getInt64(r.Record, "total_amount") }

func (r *OrdersRecord) SetTotalAmount(v int64) { r.Set("total_amount", v) }

func (r *OrdersRecord) IdempotencyKey() string { return r.GetString("idempotency_key") }

func (r *OrdersRecord) SetIdempotencyKey(v string) { r.Set("idempotency_key", v) }

func (r *OrdersRecord) AccessTokenHash() string { return r.GetString("access_token_hash") }

func (r *OrdersRecord) SetAccessTokenHash(v string) { r.Set("access_token_hash", v) }

func (r *OrdersRecord) SquareOrderID() string { return r.GetString("square_order_id") }

func (r *OrdersRecord) SetSquareOrderID(v string) { r.Set("square_order_id", v) }

func (r *OrdersRecord) SquareOrderVersion() int64 { return getInt64(r.Record, "square_order_version") }

func (r *OrdersRecord) SetSquareOrderVersion(v int64) { r.Set("square_order_version", v) }

func (r *OrdersRecord) SquarePaymentLinkID() string { return r.GetString("square_payment_link_id") }

func (r *OrdersRecord) SetSquarePaymentLinkID(v string) { r.Set("square_payment_link_id", v) }

func (r *OrdersRecord) SquarePaymentID() string { return r.GetString("square_payment_id") }

func (r *OrdersRecord) SetSquarePaymentID(v string) { r.Set("square_payment_id", v) }

func (r *OrdersRecord) CheckoutURL() string { return r.GetString("checkout_url") }

func (r *OrdersRecord) SetCheckoutURL(v string) { r.Set("checkout_url", v) }

func (r *OrdersRecord) EstimatedReadyAt() time.Time { return getTime(r.Record, "estimated_ready_at") }

func (r *OrdersRecord) SetEstimatedReadyAt(v time.Time) { setTime(r.Record, "estimated_ready_at", v) }

func (r *OrdersRecord) PaidAt() time.Time { return getTime(r.Record, "paid_at") }

func (r *OrdersRecord) SetPaidAt(v time.Time) { setTime(r.Record, "paid_at", v) }

func (r *OrdersRecord) CompletedAt() time.Time { return getTime(r.Record, "completed_at") }

func (r *OrdersRecord) SetCompletedAt(v time.Time) { setTime(r.Record, "completed_at", v) }

func (r *OrdersRecord) LastSyncedAt() time.Time { return getTime(r.Record, "last_synced_at") }

func (r *OrdersRecord) SetLastSyncedAt(v time.Time) { setTime(r.Record, "last_synced_at", v) }

// OrdersStatus mirrors the options of orders.status.
type OrdersStatus string

const (
	OrdersStatusPendingPayment OrdersStatus = "pending_payment"
	OrdersStatusPaid           OrdersStatus = "paid"
	OrdersStatusPreparing      OrdersStatus = "preparing"
	OrdersStatusReady          OrdersStatus = "ready"
	OrdersStatusCompleted      OrdersStatus = "completed"
	OrdersStatusCancelled      OrdersStatus = "cancelled"
)

// OrdersStatusValues lists every option of orders.status.
var OrdersStatusValues = []OrdersStatus{OrdersStatusPendingPayment, OrdersStatusPaid, OrdersStatusPreparing, OrdersStatusReady, OrdersStatusCompleted, OrdersStatusCancelled}

// Orders holds typed column references for building "orders" queries.
var Orders = struct {
	ID                  Column[OrdersID]
	Status              Column[OrdersStatus]
	CustomerName        Column[string]
	CustomerEmail       Column[string]
	CustomerPhone       Column[string]
	Notes               Column[string]
	Created             Column[time.Time]
	Updated             Column[time.Time]
	User                Column[UsersID]
	Currency            Column[string]
	SubtotalAmount      Column[int64]
	TaxAmount           Column[int64]
	TotalAmount         Column[int64]
	IdempotencyKey      Column[string]
	AccessTokenHash     Column[string]
	SquareOrderID       Column[string]
	SquareOrderVersion  Column[int64]
	SquarePaymentLinkID Column[string]
	SquarePaymentID     Column[string]
	CheckoutURL         Column[string]
	EstimatedReadyAt    Column[time.Time]
	PaidAt              Column[time.Time]
	CompletedAt         Column[time.Time]
	LastSyncedAt        Column[time.Time]
}{
	ID:                  Column[OrdersID]{name: "id"},
	Status:              Column[OrdersStatus]{name: "status"},
	CustomerName:        Column[string]{name: "customer_name"},
	CustomerEmail:       Column[string]{name: "customer_email"},
	CustomerPhone:       Column[string]{name: "customer_phone"},
	Notes:               Column[string]{name: "notes"},
	Created:             Column[time.Time]{name: "created"},
	Updated:             Column[time.Time]{name: "updated"},
	User:                Column[UsersID]{name: "user"},
	Currency:            Column[string]{name: "currency"},
	SubtotalAmount:      Column[int64]{name: "subtotal_amount"},
	TaxAmount:           Column[int64]{name: "tax_amount"},
	TotalAmount:         Column[int64]{name: "total_amount"},
	IdempotencyKey:      Column[string]{name: "idempotency_key"},
	AccessTokenHash:     Column[string]{name: "access_token_hash"},
	SquareOrderID:       Column[string]{name: "square_order_id"},
	SquareOrderVersion:  Column[int64]{name: "square_order_version"},
	SquarePaymentLinkID: Column[string]{name: "square_payment_link_id"},
	SquarePaymentID:     Column[string]{name: "square_payment_id"},
	CheckoutURL:         Column[string]{name: "checkout_url"},
	EstimatedReadyAt:    Column[time.Time]{name: "estimated_ready_at"},
	PaidAt:              Column[time.Time]{name: "paid_at"},
	CompletedAt:         Column[time.Time]{name: "completed_at"},
	LastSyncedAt:        Column[time.Time]{name: "last_synced_at"},
}

var OrdersSpec = CollectionSpec{
	Name: "orders",
	Type: "base",
	Fields: []FieldSpec{
		{Name: "status", Type: "select", Values: []string{"pending_payment", "paid", "preparing", "ready", "completed", "cancelled"}},
		{Name: "customer_name", Type: "text"},
		{Name: "customer_email", Type: "email"},
		{Name: "customer_phone", Type: "text"},
		{Name: "notes", Type: "text"},
		{Name: "created", Type: "autodate"},
		{Name: "updated", Type: "autodate"},
		{Name: "user", Type: "relation", Relation: "users"},
		{Name: "line_items", Type: "json"},
		{Name: "currency", Type: "text"},
		{Name: "subtotal_amount", Type: "number", OnlyInt: true},
		{Name: "tax_amount", Type: "number", OnlyInt: true},
		{Name: "total_amount", Type: "number", OnlyInt: true},
		{Name: "idempotency_key", Type: "text"},
		{Name: "access_token_hash", Type: "text"},
		{Name: "square_order_id", Type: "text"},
		{Name: "square_order_version", Type: "number", OnlyInt: true},
		{Name: "square_payment_link_id", Type: "text"},
		{Name: "square_payment_id", Type: "text"},
		{Name: "checkout_url", Type: "text"},
		{Name: "estimated_ready_at", Type: "date"},
		{Name: "paid_at", Type: "date"},
		{Name: "completed_at", Type: "date"},
		{Name: "last_synced_at", Type: "date"},
	},
}

// ---------------------------------------------------------------------------
// webhook_events
// ---------------------------------------------------------------------------

const WebhookEventsCollection = "webhook_events"

// WebhookEventsID is the ID of a "webhook_events" record.
type WebhookEventsID string

// WebhookEventsRecord is a typed proxy for a "webhook_events" record.
type WebhookEventsRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*WebhookEventsRecord)(nil)

func (*WebhookEventsRecord) CollectionName() string { return WebhookEventsCollection }

func (r *WebhookEventsRecord) ID() WebhookEventsID { return WebhookEventsID(r.Id) }

func (r *WebhookEventsRecord) EventID() string { return r.GetString("event_id") }

func (r *WebhookEventsRecord) SetEventID(v string) { r.Set("event_id", v) }

func (r *WebhookEventsRecord) EventType() string { return r.GetString("event_type") }

func (r *WebhookEventsRecord) SetEventType(v string) { r.Set("event_type", v) }

func (r *WebhookEventsRecord) Created() time.Time { return getTime(r.Record, "created") }

// WebhookEvents holds typed column references for building "webhook_events" queries.
var WebhookEvents = struct {
	ID        Column[WebhookEventsID]
	EventID   Column[string]
	EventType Column[string]
	Created   Column[time.Time]
}{
	ID:        Column[WebhookEventsID]{name: "id"},
	EventID:   Column[string]{name: "event_id"},
	EventType: Column[string]{name: "event_type"},
	Created:   Column[time.Time]{name: "created"},
}

var WebhookEventsSpec = CollectionSpec{
	Name: "webhook_events",
	Type: "base",
	Fields: []FieldSpec{
		{Name: "event_id", Type: "text"},
		{Name: "event_type", Type: "text"},
		{Name: "created", Type: "autodate"},
	},
}

// ---------------------------------------------------------------------------
// users
// ---------------------------------------------------------------------------

const UsersCollection = "users"

// UsersID is the ID of a "users" record.
type UsersID string

// UsersRecord is a typed proxy for a "users" record.
type UsersRecord struct {
	core.BaseRecordProxy
}

var _ core.RecordProxy = (*UsersRecord)(nil)

func (*UsersRecord) CollectionName() string { return UsersCollection }

func (r *UsersRecord) ID() UsersID { return UsersID(r.Id) }

func (r *UsersRecord) Email() string { return r.GetString("email") }

func (r *UsersRecord) SetEmail(v string) { r.Set("email", v) }

func (r *UsersRecord) EmailVisibility() bool { return r.GetBool("emailVisibility") }

func (r *UsersRecord) SetEmailVisibility(v bool) { r.Set("emailVisibility", v) }

func (r *UsersRecord) Verified() bool { return r.GetBool("verified") }

func (r *UsersRecord) SetVerified(v bool) { r.Set("verified", v) }

func (r *UsersRecord) Name() string { return r.GetString("name") }

func (r *UsersRecord) SetName(v string) { r.Set("name", v) }

func (r *UsersRecord) Created() time.Time { return getTime(r.Record, "created") }

func (r *UsersRecord) Updated() time.Time { return getTime(r.Record, "updated") }

func (r *UsersRecord) Phone() string { return r.GetString("phone") }

func (r *UsersRecord) SetPhone(v string) { r.Set("phone", v) }

// Users holds typed column references for building "users" queries.
var Users = struct {
	ID              Column[UsersID]
	Email           Column[string]
	EmailVisibility Column[bool]
	Verified        Column[bool]
	Name            Column[string]
	Created         Column[time.Time]
	Updated         Column[time.Time]
	Phone           Column[string]
}{
	ID:              Column[UsersID]{name: "id"},
	Email:           Column[string]{name: "email"},
	EmailVisibility: Column[bool]{name: "emailVisibility"},
	Verified:        Column[bool]{name: "verified"},
	Name:            Column[string]{name: "name"},
	Created:         Column[time.Time]{name: "created"},
	Updated:         Column[time.Time]{name: "updated"},
	Phone:           Column[string]{name: "phone"},
}

var UsersSpec = CollectionSpec{
	Name: "users",
	Type: "auth",
	Fields: []FieldSpec{
		{Name: "email", Type: "email"},
		{Name: "emailVisibility", Type: "bool"},
		{Name: "verified", Type: "bool"},
		{Name: "name", Type: "text"},
		{Name: "created", Type: "autodate"},
		{Name: "updated", Type: "autodate"},
		{Name: "phone", Type: "text"},
	},
}
