// Code generated by tygo. DO NOT EDIT.
/**
 * GENERATED FILE — do not edit by hand.
 * Source: backend/internal/views/*.go
 * Regenerate with `npm run typegen:api`.
 */

//////////
// source: checkout.go

/**
 * CheckoutItemInput and CheckoutInput are the wire shapes the frontend posts
 * to POST /api/checkout — the request-side counterpart to ProductView and
 * OrderView. Kept here (rather than in the controllers package) so tygo can
 * generate lib/api-types.ts from this one package; see backend/tygo.yaml.
 */
export interface CheckoutItemInput {
  slug: string;
  qty: number /* int */;
  options: string[];
}
export interface CheckoutInput {
  customerName: string;
  customerEmail: string;
  customerPhone?: string;
  notes?: string;
  items: CheckoutItemInput[];
}

//////////
// source: order.go

export interface OrderItemView {
  slug: string;
  name: string;
  unitPrice: number /* float64 */;
  qty: number /* int */;
  options: string[];
}
export interface OrderView {
  id: string;
  status: import("./pocketbase-types").OrdersStatusOptions;
  customerName: string;
  customerEmail: string;
  items: OrderItemView[];
  subtotal: number /* float64 */;
  subtotalFormatted: string;
  created: string;
}

//////////
// source: product.go

/**
 * ProductView is the JSON shape returned to the frontend, kept separate from
 * the Model so the wire contract (camelCase, computed fields) can evolve
 * without touching how products are read from PocketBase.
 */
export interface ProductView {
  id: string;
  slug: string;
  name: string;
  category: import("./pocketbase-types").ProductsCategoryOptions;
  price: number /* float64 */;
  priceFormatted: string;
  tagline: string;
  description: string;
  ingredients: string[];
  size?: string;
  bases?: string[];
  pour: PourView;
  badge?: string;
}
export interface PourView {
  top: string;
  bottom: string;
}
